<?php

/**
 * UI-phase Maternal Care non-resident candidates.
 * Includes male records and a resident-name collision so listing filters can
 * prove exclusion. Not persisted.
 */
return [
    [
        'key' => 'ana-p-villanueva',
        'full_name' => 'Ana P. Villanueva',
        'first_name' => 'Ana',
        'middle_name' => 'P.',
        'last_name' => 'Villanueva',
        'sex' => 'Female',
        'age' => 28,
        'birthday' => '1998-03-12',
        'status' => 'Married',
        'complete_address' => '14 Mabini Street, Barangay San Roque, Iriga City, Camarines Sur',
        'barangay' => 'San Roque',
        'year' => '2026',
        'lmp' => '07-08-24',
        'gravida_parity' => '2-1',
        'edd' => '04-20-25',
        'delivery_type' => 'CS',
        'trimester' => '3rd',
        'prenatal_visits' => '2',
        'is_high_risk' => true,
        'is_due_prenatal' => true,
        'is_delivered' => false,
        'is_incomplete_prenatal' => true,
    ],
    [
        'key' => 'hazel-d-cruz',
        'full_name' => 'Hazel D. Cruz',
        'first_name' => 'Hazel',
        'middle_name' => 'D.',
        'last_name' => 'Cruz',
        'sex' => 'Female',
        'age' => 22,
        'birthday' => '2004-06-04',
        'status' => 'Single',
        'complete_address' => '8 Bonifacio Avenue, Barangay Iraya, Iriga City, Camarines Sur',
        'barangay' => 'Iraya',
        'year' => '2026',
        'lmp' => '02-14-25',
        'gravida_parity' => '1-0',
        'edd' => '11-21-25',
        'delivery_type' => 'VD',
        'trimester' => '2nd',
        'prenatal_visits' => '3',
        'is_high_risk' => false,
        'is_due_prenatal' => true,
        'is_delivered' => false,
        'is_incomplete_prenatal' => false,
    ],
    [
        'key' => 'ramon-t-bautista',
        'full_name' => 'Ramon T. Bautista',
        'sex' => 'Male',
        'age' => 31,
        'barangay' => 'San Roque',
        'year' => '2026',
        'lmp' => '01-01-25',
        'gravida_parity' => '0-0',
        'edd' => '10-08-25',
        'delivery_type' => 'VD',
        'trimester' => '1st',
        'prenatal_visits' => '1',
    ],
    [
        'key' => 'maria-santos-collision',
        'full_name' => 'Maria Santos',
        'sex' => 'Female',
        'age' => 38,
        'barangay' => 'La Medalla',
        'year' => '2026',
        'lmp' => '05-01-25',
        'gravida_parity' => '4-3',
        'edd' => '02-05-26',
        'delivery_type' => 'VD',
        'trimester' => '1st',
        'prenatal_visits' => '1',
    ],
];
