<?php

/**
 * UI-phase fixture: Health Records → Child Care → Non-Resident / unregistered children.
 *
 * Not persisted. Classification is applied in HealthRecordsNonResidentChildCare
 * against Household Profiling DemoCatalog member full names.
 *
 * Records whose normalized full name matches a household member MUST be excluded
 * from the listing (resident). Remaining rows are Non-Resident / Unregistered.
 *
 * Year filter is driven by birthday year.
 *
 * @return list<array<string, mixed>>
 */
return [
    // Resident duplicates — must be classified out of the Non-Residents listing.
    [
        'key' => 'kristine-b-reyes',
        'first_name' => 'Kristine',
        'middle_name' => 'B.',
        'last_name' => 'Reyes',
        'mother_first_name' => 'Kristine',
        'mother_middle_name' => '',
        'mother_last_name' => 'Reyes',
        'birthday' => '2026-05-04',
        'sex' => 'Female',
        'address_zone' => 'Zone 2',
        'barangay' => 'Brgy. La Medalla',
        'municipality' => 'Iriga City',
        'school_name' => '',
        'grade_level' => 'N/A',
        'health_status' => 'Normal',
    ],
    [
        'key' => 'jacob-a-magistrado',
        'first_name' => 'Jacob',
        'middle_name' => 'A.',
        'last_name' => 'Magistrado',
        'mother_first_name' => 'Maria',
        'mother_middle_name' => '',
        'mother_last_name' => 'Magistrado',
        'birthday' => '2026-07-10',
        'sex' => 'Male',
        'address_zone' => 'Zone 2',
        'barangay' => 'Brgy. La Medalla',
        'municipality' => 'Iriga City',
        'school_name' => '',
        'grade_level' => 'N/A',
        'health_status' => 'Normal',
    ],
    [
        'key' => 'haziel-h-santos',
        'first_name' => 'Haziel',
        'middle_name' => 'H.',
        'last_name' => 'Santos',
        'mother_first_name' => 'Maria',
        'mother_middle_name' => '',
        'mother_last_name' => 'Santos',
        'birthday' => '2026-02-05',
        'sex' => 'Male',
        'address_zone' => 'Zone 2',
        'barangay' => 'Brgy. La Medalla',
        'municipality' => 'Iriga City',
        'school_name' => '',
        'grade_level' => 'N/A',
        'health_status' => 'Normal',
    ],

    // Non-residents — no normalized full-name match in Household Profiling.
    [
        'key' => 'andrei-b-malaya',
        'first_name' => 'Andrei',
        'middle_name' => 'B.',
        'last_name' => 'Malaya',
        'mother_first_name' => 'Liza',
        'mother_middle_name' => 'B.',
        'mother_last_name' => 'Malaya',
        'birthday' => '2026-04-12',
        'sex' => 'Male',
        'address_zone' => 'Zone 3',
        'barangay' => 'Brgy. San Jose',
        'municipality' => 'Iriga City',
        'school_name' => '',
        'grade_level' => 'N/A',
        'health_status' => 'Normal',
        'measurements' => [
            [
                'id' => 'NR-CC-NUT-AND-001',
                'date' => '2026-06-12',
                'weight_kg' => 6.1,
                'height_cm' => 61.0,
                'muac_cm' => 13.2,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Normal',
                'remarks' => '',
            ],
        ],
        'deworming_records' => [
            [
                'id' => 'NR-CC-DW-AND-001',
                'year' => '2026',
                'round' => '1',
                'se_status' => 'Non-NHTS',
                'date_given' => '2026-07-01',
                'remarks' => '',
            ],
        ],
    ],
    [
        'key' => 'crisley-f-fernando',
        'first_name' => 'Crisley',
        'middle_name' => 'F.',
        'last_name' => 'Fernando',
        'mother_first_name' => 'Ana',
        'mother_middle_name' => 'F.',
        'mother_last_name' => 'Fernando',
        'birthday' => '2025-08-01',
        'sex' => 'Female',
        'address_zone' => 'Poblacion',
        'barangay' => 'Brgy. Del Rosario',
        'municipality' => 'Naga City',
        'school_name' => '',
        'grade_level' => 'N/A',
        'health_status' => 'Normal',
        'measurements' => [
            [
                'id' => 'NR-CC-NUT-CRI-001',
                'date' => '2025-11-01',
                'weight_kg' => 7.2,
                'height_cm' => 68.0,
                'muac_cm' => 13.8,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Normal',
                'remarks' => '',
            ],
            [
                'id' => 'NR-CC-NUT-CRI-002',
                'date' => '2026-02-01',
                'weight_kg' => 8.0,
                'height_cm' => 71.5,
                'muac_cm' => 14.0,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Normal',
                'remarks' => '',
            ],
            [
                'id' => 'NR-CC-NUT-CRI-003',
                'date' => '2026-07-01',
                'weight_kg' => 8.6,
                'height_cm' => 74.0,
                'muac_cm' => 14.2,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Normal',
                'remarks' => '',
            ],
        ],
        'deworming_records' => [
            [
                'id' => 'NR-CC-DW-CRI-001',
                'year' => '2026',
                'round' => '1',
                'se_status' => 'Non-NHTS',
                'date_given' => '2026-06-15',
                'remarks' => '',
            ],
        ],
    ],
    [
        'key' => 'gabriel-allan-s-chua',
        'first_name' => 'Gabriel Allan',
        'middle_name' => 'S.',
        'last_name' => 'Chua',
        'mother_first_name' => 'Michelle',
        'mother_middle_name' => 'S.',
        'mother_last_name' => 'Chua',
        'birthday' => '2024-06-15',
        'sex' => 'Male',
        'address_zone' => 'Zone 1',
        'barangay' => 'Brgy. Mabulo',
        'municipality' => 'Naga City',
        'school_name' => '',
        'grade_level' => 'N/A',
        'health_status' => 'Normal',
        'measurements' => [
            [
                'id' => 'NR-CC-NUT-GAB-001',
                'date' => '2025-01-15',
                'weight_kg' => 7.4,
                'height_cm' => 67.0,
                'muac_cm' => 13.5,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Normal',
                'remarks' => '',
            ],
            [
                'id' => 'NR-CC-NUT-GAB-002',
                'date' => '2025-08-15',
                'weight_kg' => 9.1,
                'height_cm' => 74.0,
                'muac_cm' => 14.1,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Normal',
                'remarks' => '',
            ],
            [
                'id' => 'NR-CC-NUT-GAB-003',
                'date' => '2026-06-15',
                'weight_kg' => 11.4,
                'height_cm' => 84.0,
                'muac_cm' => 14.8,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Normal',
                'remarks' => '',
            ],
        ],
        'deworming_records' => [
            [
                'id' => 'NR-CC-DW-GAB-003',
                'year' => '2026',
                'round' => '2',
                'se_status' => 'Non-NHTS',
                'date_given' => '2026-07-01',
                'remarks' => 'No concern',
            ],
            [
                'id' => 'NR-CC-DW-GAB-002',
                'year' => '2026',
                'round' => '1',
                'se_status' => 'Non-NHTS',
                'date_given' => '2026-01-20',
                'remarks' => '',
            ],
            [
                'id' => 'NR-CC-DW-GAB-001',
                'year' => '2025',
                'round' => '1',
                'se_status' => 'Non-NHTS',
                'date_given' => '2025-07-15',
                'remarks' => '',
            ],
        ],
    ],
    [
        'key' => 'roselyn-a-mendoza',
        'first_name' => 'Roselyn',
        'middle_name' => 'A.',
        'last_name' => 'Mendoza',
        'mother_first_name' => 'Carmen',
        'mother_middle_name' => 'A.',
        'mother_last_name' => 'Mendoza',
        'birthday' => '2025-11-08',
        'sex' => 'Female',
        'address_zone' => 'Zone 2',
        'barangay' => 'Brgy. San Jose',
        'municipality' => 'Sagnay, Cam Sur',
        'school_name' => '',
        'grade_level' => 'N/A',
        'health_status' => 'Normal',
    ],
    [
        'key' => 'sofia-l-navarro',
        'first_name' => 'Sofia',
        'middle_name' => 'L.',
        'last_name' => 'Navarro',
        'mother_first_name' => 'Elena',
        'mother_middle_name' => 'L.',
        'mother_last_name' => 'Navarro',
        'birthday' => '2024-01-20',
        'sex' => 'Female',
        'address_zone' => 'Sitio Centro',
        'barangay' => 'Brgy. San Isidro',
        'municipality' => 'Iriga City',
        'school_name' => 'San Isidro Learning Center',
        'grade_level' => 'Kinder',
        'health_status' => 'Needs Monitoring',
        'measurements' => [
            [
                'id' => 'NR-CC-NUT-SOF-001',
                'date' => '2025-08-20',
                'weight_kg' => 9.8,
                'height_cm' => 78.0,
                'muac_cm' => 13.0,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Needs Monitoring',
                'remarks' => '',
            ],
            [
                'id' => 'NR-CC-NUT-SOF-002',
                'date' => '2026-04-20',
                'weight_kg' => 10.6,
                'height_cm' => 83.0,
                'muac_cm' => 13.4,
                'weight_for_age' => '',
                'height_for_age' => '',
                'status' => 'Needs Monitoring',
                'remarks' => '',
            ],
        ],
        'deworming_records' => [
            [
                'id' => 'NR-CC-DW-SOF-001',
                'year' => '2026',
                'round' => '1',
                'se_status' => 'Non-NHTS',
                'date_given' => '2026-03-10',
                'remarks' => '',
            ],
        ],
    ],
];
