<?php

/**
 * UI-only demo notifications for verified resident chatbot preview.
 * Not loaded from database — replace with authenticated household schedules later.
 */

return [
    [
        'id' => 'n1',
        'service' => 'Child Immunization',
        'service_short' => 'Immunization',
        'member_name' => 'Jane Doe',
        'relationship' => 'Daughter',
        'date' => 'July 29, 2026',
        'time' => '9:00 AM',
        'place' => 'Barangay Health Center',
        'status' => 'upcoming',
        'icon' => 'bi-shield-plus',
        'is_read' => false,
        'reminder_html' => 'Hello <strong>John Doe</strong>. Your <strong>daughter</strong>, <strong>Jane Doe</strong>, has an upcoming <strong>Child Immunization</strong> schedule on <strong>July 29, 2026</strong> at <strong>9:00 AM</strong> at the <strong>Barangay Health Center</strong>. Please bring her vaccination card and arrive at least 15 minutes before the scheduled time.',
    ],
    [
        'id' => 'n2',
        'service' => 'Nutrition Follow-up',
        'service_short' => 'Nutrition Follow-up',
        'member_name' => 'Mark Doe',
        'relationship' => 'Son',
        'date' => 'August 5, 2026',
        'time' => '10:30 AM',
        'place' => 'Barangay Health Center',
        'status' => 'upcoming',
        'icon' => 'bi-heart-pulse',
        'is_read' => false,
        'reminder_html' => 'Hello <strong>John Doe</strong>. Your <strong>son</strong>, <strong>Mark Doe</strong>, has an upcoming <strong>Nutrition Follow-up</strong> on <strong>August 5, 2026</strong> at <strong>10:30 AM</strong> at the <strong>Barangay Health Center</strong>. Please bring his health record and any growth monitoring notes from your last visit.',
    ],
    [
        'id' => 'n3',
        'service' => 'Prenatal Checkup',
        'service_short' => 'Prenatal Checkup',
        'member_name' => 'Maria Doe',
        'relationship' => 'Spouse',
        'date' => 'August 12, 2026',
        'time' => '8:30 AM',
        'place' => 'Barangay Health Center',
        'status' => 'upcoming',
        'icon' => 'bi-person-hearts',
        'is_read' => false,
        'reminder_html' => 'Hello <strong>John Doe</strong>. Your <strong>spouse</strong>, <strong>Maria Doe</strong>, has an upcoming <strong>Prenatal Checkup</strong> on <strong>August 12, 2026</strong> at <strong>8:30 AM</strong> at the <strong>Barangay Health Center</strong>. Please bring her maternal health record and arrive on time for assessment.',
    ],
    [
        'id' => 'n4',
        'service' => 'Deworming',
        'service_short' => 'Deworming',
        'member_name' => 'Mark Doe',
        'relationship' => 'Son',
        'date' => 'July 22, 2026',
        'time' => '1:00 PM',
        'place' => 'Barangay Health Center',
        'status' => 'today',
        'icon' => 'bi-capsule',
        'is_read' => true,
        'reminder_html' => 'Hello <strong>John Doe</strong>. Your <strong>son</strong>, <strong>Mark Doe</strong>, has a <strong>Deworming</strong> schedule <strong>today</strong>, <strong>July 22, 2026</strong> at <strong>1:00 PM</strong> at the <strong>Barangay Health Center</strong>. Please ensure he has eaten a light meal and bring his health card.',
    ],
    [
        'id' => 'n5',
        'service' => 'Senior Citizen Checkup',
        'service_short' => 'Senior Checkup',
        'member_name' => 'Pedro Doe',
        'relationship' => 'Father',
        'date' => 'June 15, 2026',
        'time' => '9:30 AM',
        'place' => 'Barangay Health Center',
        'status' => 'completed',
        'icon' => 'bi-person-check',
        'is_read' => true,
        'reminder_html' => 'Hello <strong>John Doe</strong>. Your <strong>father</strong>, <strong>Pedro Doe</strong>, completed a <strong>Senior Citizen Checkup</strong> on <strong>June 15, 2026</strong> at the <strong>Barangay Health Center</strong>. Keep any follow-up instructions from the health worker for home care.',
    ],
];
