<?php

/*
 | Demo Health Workers catalog — UI preview only.
 | Not persisted. Not loaded from the database. No CRUD.
 | Extra fields support the Edit Health Worker 5-step form.
 */

return [
    [
        'id' => 'hw-001',
        'name' => 'Admin Sarah',
        'role' => 'BHW',
        'zone' => 'Zone 1',
        'status' => 'Active',
        'photo' => null,
        'first_name' => 'Sarah',
        'last_name' => 'Santos',
        'middle_name' => 'Cruz',
        'suffix' => 'N/A',
        'sex' => 'Female',
        'date_of_birth' => '1990-04-01',
        'civil_status' => 'Single',
        'nationality' => 'Filipino',
        'mobile' => '0912 345 6789',
        'email' => 'sarah.santos@example.com',
        'house_no' => '12',
        'street' => 'Sampaguita St.',
        'purok_zone' => 'Zone 1',
        'barangay' => 'La Medalla',
        'municipality' => 'Iriga City',
        'province' => 'Camarines Sur',
        'zip_code' => '4431',
        'assigned_barangay' => 'La Medalla',
        'assigned_zone' => 'Zone 1',
        'date_appointed' => '2020-01-15',
        'end_of_appointment' => '2030-12-31',
        'username' => 'sarah.santos',
    ],
    [
        'id' => 'hw-002',
        'name' => 'Admin Sarah',
        'role' => 'BHW',
        'zone' => 'Zone 1',
        'status' => 'Active',
        'photo' => null,
        'first_name' => 'Maria',
        'last_name' => 'Reyes',
        'middle_name' => 'Domingo',
        'suffix' => 'N/A',
        'sex' => 'Female',
        'date_of_birth' => '1990-02-02',
        'civil_status' => 'Single',
        'nationality' => 'Filipino',
        'mobile' => '0921 234 5678',
        'email' => 'mariareyes@gmail.com',
        'house_no' => '123',
        'street' => 'Laguna St.',
        'purok_zone' => 'Zone 1',
        'barangay' => 'La Medalla',
        'municipality' => 'Iriga City',
        'province' => 'Camarines Sur',
        'zip_code' => '4431',
        'assigned_barangay' => 'La Medalla',
        'assigned_zone' => 'Zone 1',
        'date_appointed' => '2020-01-01',
        'end_of_appointment' => '2030-12-31',
        'username' => 'mariayreyes',
    ],
    [
        'id' => 'hw-003',
        'name' => 'Admin Sarah',
        'role' => 'BNS',
        'zone' => 'Zone 2',
        'status' => 'Active',
        'photo' => null,
        'first_name' => 'Ana',
        'last_name' => 'Lopez',
        'middle_name' => 'Garcia',
        'suffix' => 'N/A',
        'sex' => 'Female',
        'date_of_birth' => '1988-07-12',
        'civil_status' => 'Married',
        'nationality' => 'Filipino',
        'mobile' => '0917 555 0101',
        'email' => 'ana.lopez@example.com',
        'house_no' => '45',
        'street' => 'Mabini St.',
        'purok_zone' => 'Zone 2',
        'barangay' => 'La Medalla',
        'municipality' => 'Iriga City',
        'province' => 'Camarines Sur',
        'zip_code' => '4431',
        'assigned_barangay' => 'La Medalla',
        'assigned_zone' => 'Zone 2',
        'date_appointed' => '2019-06-01',
        'end_of_appointment' => '2030-12-31',
        'username' => 'ana.lopez',
    ],
    [
        'id' => 'hw-004',
        'name' => 'Admin Sarah',
        'role' => 'BHW',
        'zone' => 'Zone 1',
        'status' => 'Inactive',
        'photo' => null,
        'first_name' => 'Jose',
        'last_name' => 'Dela Cruz',
        'middle_name' => 'Ramos',
        'suffix' => 'Jr.',
        'sex' => 'Male',
        'date_of_birth' => '1985-11-20',
        'civil_status' => 'Married',
        'nationality' => 'Filipino',
        'mobile' => '0918 222 3344',
        'email' => 'jose.delacruz@example.com',
        'house_no' => '8',
        'street' => 'Rizal Ave.',
        'purok_zone' => 'Zone 1',
        'barangay' => 'La Medalla',
        'municipality' => 'Iriga City',
        'province' => 'Camarines Sur',
        'zip_code' => '4431',
        'assigned_barangay' => 'La Medalla',
        'assigned_zone' => 'Zone 1',
        'date_appointed' => '2018-03-10',
        'end_of_appointment' => '2024-12-31',
        'username' => 'jose.delacruz',
    ],
    [
        'id' => 'hw-005',
        'name' => 'Admin Sarah',
        'role' => 'BSPO',
        'zone' => 'Zone 3',
        'status' => 'Active',
        'photo' => null,
        'first_name' => 'Liza',
        'last_name' => 'Mendoza',
        'middle_name' => 'Torres',
        'suffix' => 'N/A',
        'sex' => 'Female',
        'date_of_birth' => '1992-09-05',
        'civil_status' => 'Single',
        'nationality' => 'Filipino',
        'mobile' => '0999 111 2233',
        'email' => 'liza.mendoza@example.com',
        'house_no' => '67',
        'street' => 'Bonifacio St.',
        'purok_zone' => 'Zone 3',
        'barangay' => 'La Medalla',
        'municipality' => 'Iriga City',
        'province' => 'Camarines Sur',
        'zip_code' => '4431',
        'assigned_barangay' => 'La Medalla',
        'assigned_zone' => 'Zone 3',
        'date_appointed' => '2021-04-20',
        'end_of_appointment' => '2030-12-31',
        'username' => 'liza.mendoza',
    ],
    [
        'id' => 'hw-006',
        'name' => 'Admin Sarah',
        'role' => 'BNS',
        'zone' => 'Zone 4',
        'status' => 'Inactive',
        'photo' => null,
        'first_name' => 'Carlo',
        'last_name' => 'Villanueva',
        'middle_name' => 'Perez',
        'suffix' => 'III',
        'sex' => 'Male',
        'date_of_birth' => '1987-01-28',
        'civil_status' => 'Widowed',
        'nationality' => 'Filipino',
        'mobile' => '0905 777 8899',
        'email' => 'carlo.villanueva@example.com',
        'house_no' => '21',
        'street' => 'Quezon St.',
        'purok_zone' => 'Zone 4',
        'barangay' => 'La Medalla',
        'municipality' => 'Iriga City',
        'province' => 'Camarines Sur',
        'zip_code' => '4431',
        'assigned_barangay' => 'La Medalla',
        'assigned_zone' => 'Zone 4',
        'date_appointed' => '2017-08-01',
        'end_of_appointment' => '2023-08-01',
        'username' => 'carlo.villanueva',
    ],
    [
        'id' => 'hw-007',
        'name' => 'Admin Sarah',
        'role' => 'Admin',
        'zone' => 'Zone 1',
        'status' => 'Active',
        'photo' => null,
        'first_name' => 'Sarah',
        'last_name' => 'Admin',
        'middle_name' => 'Marie',
        'suffix' => 'N/A',
        'sex' => 'Female',
        'date_of_birth' => '1989-05-18',
        'civil_status' => 'Single',
        'nationality' => 'Filipino',
        'mobile' => '0917 888 0011',
        'email' => 'sarah.admin@example.com',
        'house_no' => '1',
        'street' => 'Health Center Rd.',
        'purok_zone' => 'Zone 1',
        'barangay' => 'La Medalla',
        'municipality' => 'Iriga City',
        'province' => 'Camarines Sur',
        'zip_code' => '4431',
        'assigned_barangay' => 'La Medalla',
        'assigned_zone' => 'Zone 1',
        'date_appointed' => '2016-01-10',
        'end_of_appointment' => '2035-12-31',
        'username' => 'sarah.admin',
    ],
];
