<?php

/**
 * UI-phase fixture: Health Records → Family Planning → Non-Resident clients.
 * Not persisted. Not linked to Household Profiling DemoFamilyPlanning.
 *
 * @return list<array<string, mixed>>
 */
return [
    [
        'key' => 'roselyn-a-mendoza',
        'first_name' => 'Roselyn',
        'middle_name' => 'A.',
        'last_name' => 'Mendoza',
        'birthday' => '1991-01-08',
        'sex' => 'Female',
        'civil_status' => 'Married',
        'address_zone' => 'Zone 2',
        'barangay' => 'Brgy. San Jose',
        'municipality' => 'Sagnay, Cam Sur',
        'method' => 'Pills',
        'start_date' => '02/09/24',
        'last_visit' => '02/09/24',
        'year' => '2024',
        'visits' => [
            [
                'id' => 'NR-FP-001',
                'visited_at' => '2024-02-09',
                'remarks' => 'No Complaints',
                'commodities' => [
                    ['name' => 'Pills', 'quantity' => 30],
                    ['name' => 'IUD', 'quantity' => 1, 'given_at' => '2024-02-10'],
                ],
            ],
        ],
    ],
    [
        'key' => 'kristine-b-reyes',
        'first_name' => 'Kristine',
        'middle_name' => 'B.',
        'last_name' => 'Reyes',
        'birthday' => '1994-03-15',
        'sex' => 'Female',
        'civil_status' => 'Married',
        'address_zone' => 'Poblacion',
        'barangay' => 'Brgy. Mabulo',
        'municipality' => 'Naga City, Cam Sur',
        'method' => 'Pills',
        'start_date' => '02/12/26',
        'last_visit' => '03/12/26',
        'year' => '2026',
        'visits' => [
            [
                'id' => 'NR-FP-002',
                'visited_at' => '2026-03-12',
                'remarks' => 'Follow-up visit; no adverse effects reported.',
                'commodities' => [
                    ['name' => 'Pills', 'quantity' => 30],
                ],
            ],
        ],
    ],
    [
        'key' => 'jacob-a-magistrado',
        'first_name' => 'Jacob',
        'middle_name' => 'A.',
        'last_name' => 'Magistrado',
        'birthday' => '1996-07-22',
        'sex' => 'Male',
        'civil_status' => 'Single',
        'address_zone' => 'Zone 1',
        'barangay' => 'Brgy. Del Rosario',
        'municipality' => 'Naga City, Cam Sur',
        'method' => 'Condom',
        'start_date' => '04/22/26',
        'last_visit' => '04/21/26',
        'year' => '2026',
        'visits' => [
            [
                'id' => 'NR-FP-003',
                'visited_at' => '2026-04-21',
                'remarks' => 'Condoms dispensed; counseling provided.',
                'commodities' => [
                    ['name' => 'Condoms', 'quantity' => 12],
                ],
            ],
        ],
    ],
    [
        'key' => 'haziel-h-santos',
        'first_name' => 'Haziel',
        'middle_name' => 'H.',
        'last_name' => 'Santos',
        'birthday' => '1986-11-03',
        'sex' => 'Female',
        'civil_status' => 'Married',
        'address_zone' => 'Zone 3',
        'barangay' => 'Brgy. Carolina',
        'municipality' => 'Naga City, Cam Sur',
        'method' => 'Pills',
        'start_date' => '02/12/26',
        'last_visit' => '05/12/26',
        'year' => '2026',
        'visits' => [],
    ],
    [
        'key' => 'andrei-b-malaya',
        'first_name' => 'Andrei',
        'middle_name' => 'B.',
        'last_name' => 'Malaya',
        'birthday' => '1987-05-18',
        'sex' => 'Male',
        'civil_status' => 'Married',
        'address_zone' => 'Zone 4',
        'barangay' => 'Brgy. San Felipe',
        'municipality' => 'Naga City, Cam Sur',
        'method' => 'BTL',
        'start_date' => '03/20/26',
        'last_visit' => '04/12/26',
        'year' => '2026',
        'visits' => [],
    ],
    [
        'key' => 'crisley-f-fernando',
        'first_name' => 'Crisley',
        'middle_name' => 'F.',
        'last_name' => 'Fernando',
        'birthday' => '1999-01-27',
        'sex' => 'Female',
        'civil_status' => 'Single',
        'address_zone' => 'Zone 2',
        'barangay' => 'Brgy. Triangulo',
        'municipality' => 'Naga City, Cam Sur',
        'method' => 'Condom',
        'start_date' => '04/22/26',
        'last_visit' => '05/29/26',
        'year' => '2026',
        'visits' => [],
    ],
    [
        'key' => 'gabriel-allan-s-chua',
        'first_name' => 'Gabriel Allan',
        'middle_name' => 'S.',
        'last_name' => 'Chua',
        'birthday' => '1988-09-09',
        'sex' => 'Male',
        'civil_status' => 'Married',
        'address_zone' => 'Zone 5',
        'barangay' => 'Brgy. Lerma',
        'municipality' => 'Naga City, Cam Sur',
        'method' => 'Injectable',
        'start_date' => '05/22/26',
        'last_visit' => '05/30/26',
        'year' => '2026',
        'visits' => [],
    ],
];
