<?php

/*
 | Demo Resident Accounts — User Management Residents tab (UI preview only).
 | Distinct from Household Requests catalog (resources/demo/residents.php).
 | Seed data only; runtime edits/deletes use session overlay via DemoResidentAccounts.
 */

return [
    [
        'id' => 'ra-001',
        'first_name' => 'Kristine',
        'middle_name' => 'Mendoza',
        'last_name' => 'Reyes',
        'name' => 'Kristine Mendoza Reyes',
        'zone' => 'Zone 2',
        'email' => 'kristine.reyes@email.com',
        'contact_number' => '09123456789',
    ],
    [
        'id' => 'ra-002',
        'first_name' => 'Melanie',
        'middle_name' => 'Arguza',
        'last_name' => 'Javier',
        'name' => 'Melanie Arguza Javier',
        'zone' => 'Zone 1',
        'email' => 'melanie.javier@email.com',
        'contact_number' => '09171234567',
    ],
    [
        'id' => 'ra-003',
        'first_name' => 'Angelica',
        'middle_name' => 'Valenzuela',
        'last_name' => 'Basalla',
        'name' => 'Angelica Valenzuela Basalla',
        'zone' => 'Zone 3',
        'email' => 'angelica.basalla@email.com',
        'contact_number' => '09219876543',
    ],
    [
        'id' => 'ra-004',
        'first_name' => 'Juan',
        'middle_name' => 'Carlos',
        'last_name' => 'Dela Cruz',
        'name' => 'Juan Carlos Dela Cruz',
        'zone' => 'Zone 1',
        'email' => 'juan.delacruz@email.com',
        'contact_number' => '09185551234',
    ],
    [
        'id' => 'ra-005',
        'first_name' => 'Maria',
        'middle_name' => 'Lourdes',
        'last_name' => 'Santos',
        'name' => 'Maria Lourdes Santos',
        'zone' => 'Zone 4',
        'email' => 'maria.santos@email.com',
        'contact_number' => '09190001122',
    ],
    [
        'id' => 'ra-006',
        'first_name' => 'Roberto',
        'middle_name' => 'Miguel',
        'last_name' => 'Garcia',
        'name' => 'Roberto Miguel Garcia',
        'zone' => 'Zone 5',
        'email' => 'roberto.garcia@email.com',
        'contact_number' => '09172223344',
    ],
    [
        'id' => 'ra-007',
        'first_name' => 'Ana',
        'middle_name' => 'Patricia',
        'last_name' => 'Lopez',
        'name' => 'Ana Patricia Lopez',
        'zone' => 'Zone 2',
        'email' => 'ana.lopez@email.com',
        'contact_number' => '09173334455',
    ],
    [
        'id' => 'ra-008',
        'first_name' => 'Carlos',
        'middle_name' => 'Eduardo',
        'last_name' => 'Mendoza',
        'name' => 'Carlos Eduardo Mendoza',
        'zone' => 'Zone 3',
        'email' => 'carlos.mendoza@email.com',
        'contact_number' => '09174445566',
    ],
    [
        'id' => 'ra-009',
        'first_name' => 'Sofia',
        'middle_name' => 'Mae',
        'last_name' => 'Villanueva',
        'name' => 'Sofia Mae Villanueva',
        'zone' => 'Zone 1',
        'email' => 'sofia.villanueva@email.com',
        'contact_number' => '09175556677',
    ],
    [
        'id' => 'ra-010',
        'first_name' => 'Mark',
        'middle_name' => 'Anthony',
        'last_name' => 'Ramos',
        'name' => 'Mark Anthony Ramos',
        'zone' => 'Zone 2',
        'email' => 'mark.ramos@email.com',
        'contact_number' => '09176667788',
    ],
    [
        'id' => 'ra-011',
        'first_name' => 'Elena',
        'middle_name' => 'Marie',
        'last_name' => 'Navarro',
        'name' => 'Elena Marie Navarro',
        'zone' => 'Zone 3',
        'email' => 'elena.navarro@email.com',
        'contact_number' => '09177778899',
    ],
    [
        'id' => 'ra-012',
        'first_name' => 'Daniel',
        'middle_name' => 'Joseph',
        'last_name' => 'Flores',
        'name' => 'Daniel Joseph Flores',
        'zone' => 'Zone 4',
        'email' => 'daniel.flores@email.com',
        'contact_number' => '09178889900',
    ],
    [
        'id' => 'ra-013',
        'first_name' => 'Patricia',
        'middle_name' => 'Anne',
        'last_name' => 'Castillo',
        'name' => 'Patricia Anne Castillo',
        'zone' => 'Zone 5',
        'email' => 'patricia.castillo@email.com',
        'contact_number' => '09179990011',
    ],
    [
        'id' => 'ra-014',
        'first_name' => 'Miguel',
        'middle_name' => 'Antonio',
        'last_name' => 'Torres',
        'name' => 'Miguel Antonio Torres',
        'zone' => 'Zone 1',
        'email' => 'miguel.torres@email.com',
        'contact_number' => '09170001122',
    ],
    [
        'id' => 'ra-015',
        'first_name' => 'Angela',
        'middle_name' => 'Rose',
        'last_name' => 'Domingo',
        'name' => 'Angela Rose Domingo',
        'zone' => 'Zone 2',
        'email' => 'angela.domingo@email.com',
        'contact_number' => '09171112233',
    ],
];
