<?php

/*
 | Demo Household Requests catalog (UI preview only).
 | Status is derived by HouseholdRequestValidator from machine-checkable fields.
 | Not persisted. Not loaded from the database.
 */

return [
    [
        'id' => 'res-001',
        'name' => 'Kristine Mendoza Reyes',
        'first_name' => 'Kristine',
        'middle_name' => 'Mendoza',
        'last_name' => 'Reyes',
        'zone' => 'Zone 2',
        'mobile' => '09123456789',
        'house_no' => '210',
        'street' => 'Leyte St.',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-10 09:15:00',
        'household_members' => [
            ['name' => 'Kristine Mendoza Reyes', 'relationship' => 'Head'],
            ['name' => 'Marco Reyes', 'relationship' => 'Spouse'],
        ],
        'duplicate_detected' => false,
    ],
    [
        'id' => 'res-002',
        'name' => 'Melanie Arguza Javier',
        'first_name' => 'Melanie',
        'middle_name' => 'Arguza',
        'last_name' => 'Javier',
        'zone' => 'Zone 1',
        'mobile' => '0912ABC6789',
        'house_no' => '45',
        'street' => 'Sampaguita St.',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-11 10:00:00',
        'household_members' => [
            ['name' => 'Melanie Arguza Javier', 'relationship' => 'Head'],
        ],
        'duplicate_detected' => false,
    ],
    [
        'id' => 'res-003',
        'name' => 'Angelica Valenzuela Basalla',
        'first_name' => 'Angelica',
        'middle_name' => 'Valenzuela',
        'last_name' => 'Basalla',
        'zone' => 'Zone 3',
        'mobile' => '09219876543',
        'house_no' => '',
        'street' => 'Rizal Ave.',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-12 14:20:00',
        'household_members' => [
            ['name' => 'Angelica Valenzuela Basalla', 'relationship' => 'Head'],
        ],
        'duplicate_detected' => false,
    ],
    [
        'id' => 'res-004',
        'name' => 'Juan Carlos Dela Cruz',
        'first_name' => 'Juan',
        'middle_name' => 'Carlos',
        'last_name' => 'Dela Cruz',
        'zone' => 'Zone 1',
        'mobile' => '09171234567',
        'house_no' => '12',
        'street' => 'Mabini St.',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-13 08:45:00',
        'household_members' => [
            ['name' => 'Juan Carlos Dela Cruz', 'relationship' => 'Head'],
            ['name' => 'Ana Dela Cruz', 'relationship' => 'Spouse'],
            ['name' => 'Luis Dela Cruz', 'relationship' => 'Child'],
        ],
        'duplicate_detected' => false,
    ],
    [
        'id' => 'res-005',
        'name' => 'Maria Lourdes Santos',
        'first_name' => 'Maria',
        'middle_name' => 'Lourdes',
        'last_name' => 'Santos',
        'zone' => 'Zone 4',
        'mobile' => '09185551234',
        'house_no' => '88',
        'street' => 'Bonifacio St.',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-14 11:30:00',
        'household_members' => [],
        'duplicate_detected' => false,
    ],
    [
        'id' => 'res-006',
        'name' => 'Roberto Miguel Garcia',
        'first_name' => 'Roberto',
        'middle_name' => 'Miguel',
        'last_name' => 'Garcia',
        'zone' => 'Zone 5',
        'mobile' => '09190001122',
        'house_no' => '5',
        'street' => 'Quezon Blvd.',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-15 16:10:00',
        'household_members' => [
            ['name' => 'Roberto Miguel Garcia', 'relationship' => 'Head'],
        ],
        'duplicate_detected' => true,
    ],
    [
        'id' => 'res-007',
        'name' => 'Ana Patricia Lopez',
        'first_name' => 'Ana',
        'middle_name' => 'Patricia',
        'last_name' => 'Lopez',
        'zone' => 'Zone 2',
        'mobile' => '+639171112233',
        'house_no' => '33',
        'street' => 'Luna St.',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-16 09:05:00',
        'household_members' => [
            ['name' => 'Ana Patricia Lopez', 'relationship' => 'Head'],
            ['name' => 'Pedro Lopez', 'relationship' => 'Child'],
        ],
        'duplicate_detected' => false,
    ],
    [
        'id' => 'res-008',
        'name' => 'Carlos Eduardo Mendoza',
        'first_name' => 'Carlos',
        'middle_name' => 'Eduardo',
        'last_name' => 'Mendoza',
        'zone' => 'Zone 3',
        'mobile' => '09172223344',
        'house_no' => '19',
        'street' => '',
        'barangay' => 'La Medalla',
        'submitted_at' => '2026-06-17 13:40:00',
        'household_members' => [
            ['name' => 'Carlos Eduardo Mendoza', 'relationship' => 'Head'],
        ],
        'duplicate_detected' => false,
    ],
];
